#!/usr/bin/env python3

import os

user_directory = os.path.expanduser('~')

config_location = f"{user_directory}/.config/fish/config.fish"

alias = input('enter alias for command: ')
command = input('enter the command: ')

command = f"echo 'alias {alias}=\"{command}\"' >> {config_location}"

print(f"adding {command} to shell config")

os.system(command)
source_command = f"source {config_location}"
